spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/restapi2
    driver-class-name: org.mariadb.jdbc.Driver
    username: restapi1
    password: 1111
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 154711632031-e6a1lsonnrt68haimdnlou81n254rdug.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

#server:
#  servlet:
#    session:
#      timeout: 43200m      # 60m * 24h * 30d
#      cookie:
#        max-age: 43200m    # 60m * 24h * 30d
#        name: SID
#        http-only: true
#        secure: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace


